#ifndef ALLDLGHEADERS_H
#define ALLDLGHEADERS_H

#include "CreateAcsDlg.h"
#include "CreateAcsItemDlg.h"
#include "CreateBlcDlg.h"
#include "CreateCltDlg.h"
#include "CreateCmpDlg.h"
#include "CreateCurDlg.h"
#include "CreateEmpDlg.h"
#include "CreateLcnDlg.h"
#include "CreateMsrDlg.h"
#include "CreateOrdDlg.h"
#include "CreateOrdListDlg.h"
#include "CreatePhtDlg.h"
#include "CreatePmtDlg.h"
#include "CreatePosDlg.h"
#include "CreatePrcDlg.h"
#include "CreateProdnDlg.h"
#include "CreateProdDlg.h"
#include "CreateProdnListDlg.h"
#include "CreatePrdTpDlg.h"
#include "CreateRelDlg.h"
#include "CreateRelTypeDlg.h"
#include "CreateRoleDlg.h"
#include "CreateRtrnDlg.h"
#include "CreateRtrnListDlg.h"
#include "CreateSlrDlg.h"
#include "CreateSlrTypeDlg.h"
#include "CreateStsDlg.h"
#include "CreateUserDlg.h"
#include "CreateWOffDlg.h"
#include "CreateWOffListDlg.h"

#endif